# Generated by Django 4.1 on 2023-04-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="password", max_length=1000),
            preserve_default=False,
        ),
    ]
